world_frame: "map"
human_name: "human"

timer_human:
  rate: 1.0 # [Hz]

timer_point:
  rate: 2.0 # [Hz]

timer_heading:
  rate: 2.0 # [Hz]

index: 0
side: 10.0
human_distance_threshold: 20.0

# Waypoint parameters
timer_waypoint:
  rate: 1.0 # [Hz]

step_size: 40.0 # [m]